export const DEVICES_STATUS_FETCHED = "DEVICES_STATUS_FETCHED";
export const DEVICES_STATUS_RESET = "DEVICES_STATUS_RESET";

export const PORTAL_STATUS_FETCHED = "PORTAL_STATUS_FETCHED";
export const PORTAL_STATUS_RESET = "PORTAL_STATUS_RESET";


export const SCAN_STARTED = "SCAN_STARTED";
export const MAT_FOUND = "MAT_FOUND";
export const SCAN_STATUS_RESET = "SCAN_STATUS_RESET";


export const SYNC_SCANS_FETCHED = "SYNC_SCANS_FETCHED";

export const LOCATION_FETCHED = "LOCATION_FETCHED";
export const SETTINGS_FETCHED = "SETTINGS_FETCHED";
