export const DEVICES_STATUS_FETCHED = 'DEVICES_STATUS_FETCHED';
export const DEVICES_CHECK_COMPLETED = 'DEVICES_CHECK_COMPLETED';

export const JOB_TYPES_FETCHED = 'JOB_TYPES_FETCHED';

export const LOCATION_FETCHED = 'LOCATION_FETCHED';
export const SETTINGS_FETCHED = 'SETTINGS_FETCHED';
